#!/bin/bash
rm -r "./Assets/Plugins/LibsSymlinks"
mkdir "./Assets/Plugins/LibsSymlinks"
mkdir "./Assets/Plugins/LibsSymlinks/Editor"
# BODY_START
ln -s "../../../PestelLib/APKIntegrityVerifier/Sources" "./Assets/Plugins/LibsSymlinks/APKIntegrityVerifier"
ln -s "../../../PestelLib/BestHTTP/Sources" "./Assets/Plugins/LibsSymlinks/BestHTTP"
ln -s "../../../PestelLib/CameraTools/Sources" "./Assets/Plugins/LibsSymlinks/CameraTools"
ln -s "../../../PestelLib/ClientConfig/Sources" "./Assets/Plugins/LibsSymlinks/ClientConfig"
ln -s "../../../../PestelLib/ClientConfig.Editor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/ClientConfig.Editor"
ln -s "../../../PestelLib/DebugMenu/Sources" "./Assets/Plugins/LibsSymlinks/DebugMenu"
ln -s "../../../PestelLib/DependencyInjection/Sources" "./Assets/Plugins/LibsSymlinks/DependencyInjection"
ln -s "../../../PestelLib/DependencyInjectionCore/Sources" "./Assets/Plugins/LibsSymlinks/DependencyInjectionCore"
ln -s "../../../PestelLib/DOTween/Sources" "./Assets/Plugins/LibsSymlinks/DOTween"
ln -s "../../../PestelLib/GoogleSpreadsheet/Sources" "./Assets/Plugins/LibsSymlinks/GoogleSpreadsheet"
ln -s "../../../../PestelLib/GoogleSpreadsheet.Editor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/GoogleSpreadsheet.Editor"
ln -s "../../../PestelLib/Localization/Sources" "./Assets/Plugins/LibsSymlinks/Localization"
ln -s "../../../PestelLib/log4net/Sources" "./Assets/Plugins/LibsSymlinks/log4net"
ln -s "../../../PestelLib/MessagePack/Sources" "./Assets/Plugins/LibsSymlinks/MessagePack"
ln -s "../../../PestelLib/NetworkUtils/Sources" "./Assets/Plugins/LibsSymlinks/NetworkUtils"
ln -s "../../../PestelLib/Newtonsoft.JsonDotNet/Sources" "./Assets/Plugins/LibsSymlinks/Newtonsoft.JsonDotNet"
ln -s "../../../../PestelLib/PackageManager.Editor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/PackageManager.Editor"
ln -s "../../../PestelLib/RandomModule/Sources" "./Assets/Plugins/LibsSymlinks/RandomModule"
rm "./ProjectLib/ConcreteSharedLogic/Sources/Modules/RandomModule"
ln -s "../../../../PestelLib/RandomModule/SourcesSL" "./ProjectLib/ConcreteSharedLogic/Sources/Modules/RandomModule"
ln -s "../../../PestelLib/SaveSystem/Sources" "./Assets/Plugins/LibsSymlinks/SaveSystem"
ln -s "../../../PestelLib/ServerClientUtils/Sources" "./Assets/Plugins/LibsSymlinks/ServerClientUtils"
ln -s "../../../PestelLib/ServerLogClient/Sources" "./Assets/Plugins/LibsSymlinks/ServerLogClient"
ln -s "../../../PestelLib/ServerLogProtocol/Sources" "./Assets/Plugins/LibsSymlinks/ServerLogProtocol"
ln -s "../../../PestelLib/ServerProtocol/Sources" "./Assets/Plugins/LibsSymlinks/ServerProtocol"
ln -s "../../../PestelLib/ServerShared/Sources" "./Assets/Plugins/LibsSymlinks/ServerShared"
ln -s "../../../PestelLib/SharedConfig/Sources" "./Assets/Plugins/LibsSymlinks/SharedConfig"
ln -s "../../../PestelLib/SharedLogicBase/Sources" "./Assets/Plugins/LibsSymlinks/SharedLogicBase"
ln -s "../../../../PestelLib/SharedLogicBase.Editor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/SharedLogicBase.Editor"
ln -s "../../../PestelLib/SharedLogicClient/Sources" "./Assets/Plugins/LibsSymlinks/SharedLogicClient"
ln -s "../../../PestelLib/SQLite/Sources" "./Assets/Plugins/LibsSymlinks/SQLite"
ln -s "../../../PestelLib/TaskQueueLib/Sources" "./Assets/Plugins/LibsSymlinks/TaskQueueLib"
ln -s "../../../PestelLib/TasksCommon/Sources" "./Assets/Plugins/LibsSymlinks/TasksCommon"
ln -s "../../../PestelLib/UI/Sources" "./Assets/Plugins/LibsSymlinks/UI"
ln -s "../../../PestelLib/UniversalSerializer/Sources" "./Assets/Plugins/LibsSymlinks/UniversalSerializer"
ln -s "../../../PestelLib/UserProfileViewer/Sources" "./Assets/Plugins/LibsSymlinks/UserProfileViewer"
ln -s "../../../../PestelLib/UserProfileViewer.Editor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/UserProfileViewer.Editor"
ln -s "../../../PestelLib/Utils/Sources" "./Assets/Plugins/LibsSymlinks/Utils"
ln -s "../../../../PestelLib/UtilsEditor/Sources" "./Assets/Plugins/LibsSymlinks/Editor/UtilsEditor"

# BODY_END
