using UnityEngine;
using System.Text.RegularExpressions;

public class BadWordsFilter {
   private static string[] english = {
      "2g1c",
      "2 girls 1 cup",
      "acrotomophilia",
      "anal",
      "anilingus",
      "anus",
      "arsehole",
      "ass",
      "asshole",
      "assmunch",
      "auto erotic",
      "autoerotic",
      "babeland",
      "baby batter",
      "ball gag",
      "ball gravy",
      "ball kicking",
      "ball licking",
      "ball sack",
      "ball sucking",
      "bangbros",
      "bareback",
      "barely legal",
      "barenaked",
      "bastardo",
      "bastinado",
      "bbw",
      "bdsm",
      "beaver cleaver",
      "beaver lips",
      "bestiality",
      "bi curious",
      "big black",
      "big breasts",
      "big knockers",
      "big tits",
      "bimbos",
      "birdlock",
      "bitch",
      "black cock",
      "blonde action",
      "blonde on blonde action",
      "blow j",
      "blow your l",
      "blue waffle",
      "blumpkin",
      "bollocks",
      "bondage",
      "boner",
      "boob",
      "boobs",
      "booty call",
      "brown showers",
      "brunette action",
      "bukkake",
      "bulldyke",
      "bullet vibe",
      "bung hole",
      "bunghole",
      "busty",
      "butt",
      "buttcheeks",
      "butthole",
      "camel toe",
      "camgirl",
      "camslut",
      "camwhore",
      "carpet muncher",
      "carpetmuncher",
      "chocolate rosebuds",
      "circlejerk",
      "cleveland steamer",
      "clit",
      "clitoris",
      "clover clamps",
      "clusterfuck",
      "cock",
      "cocks",
      "coprolagnia",
      "coprophilia",
      "cornhole",
      "cum",
      "cumming",
      "cunnilingus",
      "cunt",
      "darkie",
      "date rape",
      "daterape",
      "deep throat",
      "deepthroat",
      "dick",
      "dildo",
      "dirty pillows",
      "dirty sanchez",
      "doggie style",
      "doggiestyle",
      "doggy style",
      "doggystyle",
      "dog style",
      "dolcett",
      "domination",
      "dominatrix",
      "dommes",
      "donkey punch",
      "double dong",
      "double penetration",
      "dp action",
      "eat my ass",
      "ecchi",
      "ejaculation",
      "erotic",
      "erotism",
      "escort",
      "ethical slut",
      "eunuch",
      "faggot",
      "fecal",
      "felch",
      "fellatio",
      "feltch",
      "female squirting",
      "femdom",
      "figging",
      "fingering",
      "fisting",
      "foot fetish",
      "footjob",
      "frotting",
      "fuck",
      "fuck buttons",
      "fudge packer",
      "fudgepacker",
      "futanari",
      "gang bang",
      "gay sex",
      "genitals",
      "giant cock",
      "girl on",
      "girl on top",
      "girls gone wild",
      "goatcx",
      "goatse",
      "gokkun",
      "golden shower",
      "goodpoop",
      "goo girl",
      "goregasm",
      "grope",
      "group sex",
      "g-spot",
      "guro",
      "hand job",
      "handjob",
      "hard core",
      "hardcore",
      "hentai",
      "homoerotic",
      "honkey",
      "hooker",
      "hot chick",
      "how to kill",
      "how to murder",
      "huge fat",
      "humping",
      "incest",
      "intercourse",
      "jack off",
      "jail bait",
      "jailbait",
      "jerk off",
      "jigaboo",
      "jiggaboo",
      "jiggerboo",
      "jizz",
      "juggs",
      "kike",
      "kinbaku",
      "kinkster",
      "kinky",
      "knobbing",
      "leather restraint",
      "leather straight jacket",
      "lemon party",
      "lolita",
      "lovemaking",
      "make me come",
      "male squirting",
      "masturbate",
      "menage a trois",
      "milf",
      "missionary position",
      "motherfucker",
      "mound of venus",
      "mr hands",
      "muff diver",
      "muffdiving",
      "nambla",
      "nawashi",
      "negro",
      "neonazi",
      "nigga",
      "nigger",
      "nig nog",
      "nimphomania",
      "nipple",
      "nipples",
      "nsfw images",
      "nude",
      "nudity",
      "nympho",
      "nymphomania",
      "octopussy",
      "omorashi",
      "one cup two girls",
      "one guy one jar",
      "orgasm",
      "orgy",
      "paedophile",
      "panties",
      "panty",
      "pedobear",
      "pedophile",
      "pegging",
      "penis",
      "phone sex",
      "piece of shit",
      "pissing",
      "piss pig",
      "pisspig",
      "playboy",
      "pleasure chest",
      "pole smoker",
      "ponyplay",
      "poof",
      "poop chute",
      "poopchute",
      "porn",
      "porno",
      "pornography",
      "prince albert piercing",
      "pthc",
      "pubes",
      "pussy",
      "queaf",
      "raghead",
      "raging boner",
      "rape",
      "raping",
      "rapist",
      "rectum",
      "reverse cowgirl",
      "rimjob",
      "rimming",
      "rosy palm",
      "rosy palm and her 5 sisters",
      "rusty trombone",
      "sadism",
      "scat",
      "schlong",
      "scissoring",
      "semen",
      "sex",
      "sexo",
      "sexy",
      "shaved beaver",
      "shaved pussy",
      "shemale",
      "shibari",
      "shit",
      "shota",
      "shrimping",
      "slanteye",
      "slut",
      "s&m",
      "smut",
      "snatch",
      "snowballing",
      "sodomize",
      "sodomy",
      "spic",
      "spooge",
      "spread legs",
      "strap on",
      "strapon",
      "strappado",
      "strip club",
      "style doggy",
      "suck",
      "sucks",
      "suicide girls",
      "sultry women",
      "swastika",
      "swinger",
      "tainted love",
      "taste my",
      "tea bagging",
      "threesome",
      "throating",
      "tied up",
      "tight white",
      "tit",
      "tits",
      "titties",
      "titty",
      "tongue in a",
      "topless",
      "tosser",
      "towelhead",
      "tranny",
      "tribadism",
      "tub girl",
      "tubgirl",
      "tushy",
      "twat",
      "twink",
      "twinkie",
      "two girls one cup",
      "undressing",
      "upskirt",
      "urethra play",
      "urophilia",
      "vagina",
      "venus mound",
      "vibrator",
      "violet blue",
      "violet wand",
      "vorarephilia",
      "voyeur",
      "vulva",
      "wank",
      "wetback",
      "wet dream",
      "white power",
      "women rapping",
      "wrapping men",
      "wrinkled starfish",
      "xx",
      "xxx",
      "yaoi",
      "yellow showers",
      "yiffy",
      "zoophilia"
   };

   private static string[] russian = {
      "пидр",
      "хуй",
      "бля",
      "выеб",
      "fuk",
      "пидор",
      "пидар",
      "мудил",
      "мудак",
      "пох",
      "похер",
      "shit",
      "fick",
      "hooi",
      "hui",
      "huj",
      "pidor",
      "mudak",
      "pidar",
      "suka",
      "шмара",
      "шлюха",
      "ебал",
      "отсоси",
      "nahui",
      "chmo",
      "blja",
      "bljad'",
      "ебу",
      "выёб",
      "ебись",
      "отсоси",
      "мудо",
      "отъеб",
      "bliad",
      "педик",
      "йопт",
      "млять",
      "пля",
      "плять",
      "чмо",
      "хер",
      "нахуй",
      "нахер",
      "блять",
      "блядь",
      "блядина",
      "гнида",
      "шалава",
      "епт",
      "епта",
      "епти",
      "сучара",
      "хуль",
      "хули",
      "хуле",
      "херли",
      "ёпт",
      "ёпта",
      "ёпти",
      "паскуда",
      "писд",
      "pox",
      "poh",
      "pohui",
      "pohuj",
      "nahuj",
      "пизд",
      "пизда",
      "пиздец",
      "далбоеб",
      "далбаеб",
      "долбаеб",
      "далбаеб",
      "ебаный",
      "ебанный",
      "хуесос",
      "херня",
      "xuy",
      "ебаная",
      "ебанная",
      "неебу",
      "ебитесь",
      "охуел",
      "bitch",
      "fck",
      "freak",
      "fuk",
      "fuck",
      "пистец",
      "мля",
      "педики",
      "чмошник",
      "чмошниц",
      "мляя",
      "блёs",
      "chlampe",
      "maul",
      "fack",
      "пляя",
      "херов",
      "ипёт",
      "ниипёт",
      "епёт",
      "мудень",
      "fick",
      "хня",
      "ибаццо",
      "ипаццо",
      "ибацца",
      "ипацца",
      "ebatsya",
      "ebatsa",
      "ebaniy",
      "ebanie",
      "ebanut",
      "pedik",
      "ёпт",
      "xuem",
      "xуem",
      "xujom",
      "huem",
      "hujom",
      "hernya",
      "xernya",
      "нах",
      "nahooi",
      "пнх",
      "zaebis",
      "ёп",
      "huli",
      "епет",
      "пздец",
      "пздц",
      "cock",
      "sukin",
      "ipalo",
      "ept",
      "хйу",
      "йух",
      "йобан",
      "hujnya",
      "дрочи",
      "епт",
      "naxer",
      "dalbaeb",
      "dalboeb",
      "dolbaeb",
      "dolboeb",
      "ebal",
      "иннах",
      "ebat",
      "xuy",
      "xuy",
      "nixer",
      "йопан",
      "mudil",
      "дроч",
      "xuj",
      "mudlo",
      "xuj",
      "бля",
      "блят",
      "покуй",
      "похую",
      "похер",
      "заеб",
      "ебан",
      "хуя",
      "хуя",
      "бляг",
      "похуй",
      "хууй",
      "hernja",
      "herovo",
      "herova",
      "herovaja",
      "herovie",
      "nahooy",
      "nahooj",
      "nahooj",
      "nahooy",
      "ебт",
      "йопт",
      "ёб",
      "педиг",
      "блеать",
      "блиать",
      "блеадь",
      "блиадь"
   };

   public static bool IsBadWord(string word) {
      word = word.ToLower().Replace(" ", string.Empty);
      word = Regex.Replace(word, @"[\d-]", string.Empty);

      for (int i = 0; i < english.Length; ++i) {
         if (english[i] == word) {
            return true;
         }
      }

      for (int i = 0; i < russian.Length; ++i) {
         if (russian[i] == word) {
            return true;
         }
      }
      return false;
   }
}
